# Generated by Django 6.0.3 on 2026-04-24 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('deleted_at', models.BigIntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diaper',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('changed_at', models.BigIntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('deleted_at', models.BigIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diapers', to='baby.child')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='Eat',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('started_at', models.BigIntegerField()),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('deleted_at', models.BigIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eats', to='baby.child')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('started_at', models.BigIntegerField()),
                ('ended_at', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.BigIntegerField()),
                ('updated_at', models.BigIntegerField()),
                ('deleted_at', models.BigIntegerField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sleeps', to='baby.child')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
