# Generated by Django 6.0.3 on 2026-04-25 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baby', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE baby_child ALTER COLUMN birth_date TYPE bigint USING EXTRACT(EPOCH FROM birth_date)::bigint * 1000",
            reverse_sql="ALTER TABLE baby_child ALTER COLUMN birth_date TYPE timestamp with time zone USING to_timestamp(birth_date / 1000.0)",
        ),
        migrations.AlterField(
            model_name='child',
            name='birth_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
